---
name: Nightly Build

on:
    push:
        branches:
            - main

jobs:
    nightly:
        name: Nightly Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: latest
                  coverage: none
                  tools: wp-cli

            - name: Install latest version of dist-archive-command
              run: wp package install wp-cli/dist-archive-command:dev-main

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Build plugin
              run: npm run build

            - name: Create ZIP file
              run: wp dist-archive . ./media-experiments.zip

            - uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  automatic_release_tag: nightly
                  prerelease: true
                  title: 'Nightly Build'
                  files: |
                      media-experiments.zip
